#!/bin/sh -
#
# Copyright (c) 1980 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
# Device "make" file.  Valid arguments:
#       std     standard devices
#       local   configuration specific devices
#       fd      file descriptor driver
# Disks:
#       sd*     flash cards SecureDigital
# Pseudo terminals:
#       pty*    set of 16 master and slave pseudo terminals

PATH=/etc:/sbin:/usr/sbin:/bin:/usr/bin
umask 77
for i
do
case $i in

std)
	mknod console		c 0 0
	mknod mem		c 1 0	; chmod 640 mem ; chgrp kmem mem
	mknod kmem		c 1 1	; chmod 640 kmem ; chgrp kmem kmem
	mknod null		c 1 2	; chmod 666 null
	mknod zero		c 1 3	; chmod 444 zero
	mknod tty		c 2 0	; chmod 666 tty
 	mknod klog		c 3 0	; chmod 600 klog
	;;

fd)
	umask 0
	rm -rf fd
	rm -f stdin stdout stderr
	mkdir fd
	chmod 755 fd
	mknod stdin c 4 0
	mknod stdout c 4 1
	mknod stderr c 4 2
	eval `echo "" | awk '{ for (i = 0; i < 32; i++)
			printf("mknod fd/%d c 4 %d; ",i,i); }'`
	;;

rd)
	umask 2
	rm -f rd[0123] rd[0123][abcd]
	mknod rd0  b 0 0
	mknod rd0a b 0 1
	mknod rd0b b 0 2
	mknod rd0c b 0 2
	mknod rd0d b 0 2
	mknod rd1  b 1 0
	mknod rd1a b 1 1
	mknod rd1b b 1 2
	mknod rd1c b 1 2
	mknod rd1d b 1 2
	mknod rd2  b 2 0
	mknod rd2a b 2 1
	mknod rd2b b 2 2
	mknod rd2c b 2 2
	mknod rd2d b 2 2
	mknod rd3  b 3 0
	mknod rd3a b 3 1
	mknod rd3b b 3 2
	mknod rd3c b 3 2
	mknod rd3d b 3 2
	chgrp operator rd[0123]
	chgrp operator rd[0123][abcd]
	chmod 640 rd[0123][abcd]
	chmod 640 rd[0123]
	;;

local)
	sh MAKEDEV.local
	;;
esac
done
