/*
 * Copyright (c) 1986 Regents of the University of California.
 * All rights reserved.  The Berkeley software License Agreement
 * specifies the terms and conditions for redistribution.
 */

/*
 * Generated by tools/gen_kernel_metadata.py from sys/kern/errlist.master.
 * Edit the master and run `bmake regen-kernel-metadata`.
 */
#include <sys/param.h>
#include <sys/errno.h>
#include <sys/systm.h>

static const char errno_message_pool[] =
    "Undefined error: 0\0"
    "Operation not permitted\0"
    "No such file or directory\0"
    "No such process\0"
    "Interrupted system call\0"
    "Input/output error\0"
    "Device not configured\0"
    "Argument list too long\0"
    "Exec format error\0"
    "Bad file descriptor\0"
    "No child processes\0"
    "No more processes\0"
    "Cannot allocate memory\0"
    "Permission denied\0"
    "Bad address\0"
    "Block device required\0"
    "Device busy\0"
    "File exists\0"
    "Cross-device link\0"
    "Operation not supported by device\0"
    "Not a directory\0"
    "Is a directory\0"
    "Invalid argument\0"
    "Too many open files in system\0"
    "Too many open files\0"
    "Inappropriate ioctl for device\0"
    "Text file busy\0"
    "File too large\0"
    "No space left on device\0"
    "Illegal seek\0"
    "Read-only file system\0"
    "Too many links\0"
    "Broken pipe\0"
    "Numerical argument out of domain\0"
    "Result too large\0"
    "Resource temporarily unavailable\0"
    "Operation now in progress\0"
    "Operation already in progress\0"
    "Socket operation on non-socket\0"
    "Destination address required\0"
    "Message too long\0"
    "Protocol wrong type for socket\0"
    "Protocol not available\0"
    "Protocol not supported\0"
    "Socket type not supported\0"
    "Operation not supported\0"
    "Protocol family not supported\0"
    "Address family not supported by protocol family\0"
    "Address already in use\0"
    "Can't assign requested address\0"
    "Network is down\0"
    "Network is unreachable\0"
    "Network dropped connection on reset\0"
    "Software caused connection abort\0"
    "Connection reset by peer\0"
    "No buffer space available\0"
    "Socket is already connected\0"
    "Socket is not connected\0"
    "Can't send after socket shutdown\0"
    "Too many references: can't splice\0"
    "Operation timed out\0"
    "Connection refused\0"
    "Too many levels of symbolic links\0"
    "File name too long\0"
    "Host is down\0"
    "No route to host\0"
    "Directory not empty\0"
    "Too many processes\0"
    "Too many users\0"
    "Disc quota exceeded\0"
    "Stale NFS file handle\0"
    "Too many levels of remote in path\0"
    "RPC struct is bad\0"
    "RPC version wrong\0"
    "RPC prog. not avail\0"
    "Program version wrong\0"
    "Bad procedure for program\0"
    "No locks available\0"
    "Function not implemented\0"
    "Inappropriate file type or format\0"
    "Authentication error\0"
    "Need authenticator\0"
    ;

static const uint16_t errno_message_offsets[] = {
    0, 19, 43, 69, 85, 109, 128, 150, 173, 191, 211, 230,
    248, 271, 289, 301, 323, 335, 347, 365, 399, 415, 430, 447,
    477, 497, 528, 543, 558, 582, 595, 617, 632, 644, 677, 694,
    727, 753, 783, 814, 843, 860, 891, 914, 937, 963, 987, 1017,
    1065, 1088, 1119, 1135, 1158, 1194, 1227, 1252, 1278, 1306, 1330, 1363,
    1397, 1417, 1436, 1470, 1489, 1502, 1519, 1539, 1558, 1573, 1593, 1615,
    1649, 1667, 1685, 1705, 1727, 1753, 1772, 1797, 1831, 1852,
};

#define ERRNO_MESSAGE_COUNT \
    (sizeof(errno_message_offsets) / sizeof(errno_message_offsets[0]))
_Static_assert(ERRNO_MESSAGE_COUNT == ELAST + 1,
    "errno metadata must cover zero through ELAST");

const char *
kernel_errmsg(u_int error)
{
    if (error >= ERRNO_MESSAGE_COUNT)
        return NULL;
    return errno_message_pool + errno_message_offsets[error];
}
