/*
 * Copyright (c) 1986 Regents of the University of California.
 * All rights reserved.  The Berkeley software License Agreement
 * specifies the terms and conditions for redistribution.
 */

/*
 * Generated by tools/gen_kernel_metadata.py from sys/kern/syscalls.master.
 * Edit the master and run `bmake regen-kernel-metadata`.
 */
#include <sys/param.h>
#include <sys/systm.h>

extern void sc_msec(void);

const uint8_t syscall_nargs[] = {
    1,
    1,
    0,
    3,
    3,
    3,
    1,
    4,
    0,
    2,
    1,
    2,
    1,
    1,
    3,
    2,
    3,
    2,
    2,
    4,
    0,
    3,
    1,
    6,
    0,
    0,
    4,
    0,
    2,
    2,
    3,
    4,
    3,
    2,
    1,
    2,
    0,
    2,
    2,
    2,
    2,
    1,
    0,
    1,
    4,
    1,
    1,
    0,
    0,
    1,
    1,
    0,
    3,
    1,
    4,
    1,
    2,
    2,
    3,
    3,
    1,
    1,
    2,
    0,
    0,
    6,
    0,
    0,
    0,
    1,
    1,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    1,
    2,
    3,
    0,
    0,
    2,
    0,
    0,
    0,
    2,
    0,
    3,
    5,
    0,
    1,
    3,
#ifdef INET
    3,
#else
    0,
#endif
#ifdef INET
    3,
#else
    0,
#endif
#ifdef INET
    3,
#else
    0,
#endif
    2,
#ifdef INET
    4,
#else
    0,
#endif
#ifdef INET
    4,
#else
    0,
#endif
    1,
#ifdef INET
    3,
#else
    0,
#endif
#ifdef INET
    5,
#else
    0,
#endif
#ifdef INET
    2,
#else
    0,
#endif
    1,
    0,
    0,
    0,
    0,
    2,
#ifdef INET
    3,
#else
    0,
#endif
#ifdef INET
    3,
#else
    0,
#endif
    0,
    2,
    2,
#ifdef INET
    5,
#else
    0,
#endif
    0,
    3,
    3,
    2,
    3,
    2,
#ifdef INET
    6,
#else
    0,
#endif
    0,
    0,
    2,
    3,
    3,
    2,
    0,
#ifdef INET
    6,
#else
    0,
#endif
#ifdef INET
    2,
#else
    0,
#endif
#ifdef INET
    4,
#else
    0,
#endif
    2,
    1,
    2,
    0,
    2,
#ifdef INET
    3,
#else
    0,
#endif
    0,
    0,
    2,
    2,
    2,
    0,
    2,
    4,
#ifdef INET
    3,
#else
    0,
#endif
    0,
    2,
    1,
    4,
    0,
};

const syscall_handler_t syscall_handlers[] = {
    nosys,
    rexit,
    fork,
    read,
    write,
    open,
    close,
    wait4,
    nosys,
    link,
    unlink,
    execv,
    chdir,
    fchdir,
    mknod,
    chmod,
    chown,
    chflags,
    fchflags,
    lseek,
    getpid,
    smount,
    umount,
    __sysctl,
    getuid,
    geteuid,
    ptrace,
    getppid,
    statfs,
    fstatfs,
    getfsstat,
    sigaction,
    sigprocmask,
    saccess,
    sigpending,
    sigaltstack,
    sync,
    kill,
    stat,
    nosys,
    lstat,
    dup,
    pipe,
    nosys,
    profil,
    setuid,
    seteuid,
    getgid,
    getegid,
    setgid,
    setegid,
    kmemdev,
    nosys,
    nosys,
    ioctl,
    reboot,
    sigwait,
    symlink,
    readlink,
    execve,
    umask,
    chroot,
    fstat,
    nosys,
    nosys,
    pselect,
    vfork,
    nosys,
    nosys,
    brk,
#ifdef GLOB_ENABLED
    rdglob,
#else
    nosys,
#endif
#ifdef GLOB_ENABLED
    wrglob,
#else
    nosys,
#endif
    sc_msec,
    nosys,
    nosys,
    nosys,
    vhangup,
    nosys,
    nosys,
    getgroups,
    setgroups,
    getpgrp,
    setpgrp,
    setitimer,
    nosys,
    nosys,
    getitimer,
    nosys,
    nosys,
    getdtablesize,
    dup2,
    nosys,
    fcntl,
    select,
    nosys,
    fsync,
    setpriority,
#ifdef INET
    socket,
#else
    nonet,
#endif
#ifdef INET
    connect,
#else
    nosys,
#endif
#ifdef INET
    accept,
#else
    nosys,
#endif
    getpriority,
#ifdef INET
    send,
#else
    nosys,
#endif
#ifdef INET
    recv,
#else
    nosys,
#endif
    sigreturn,
#ifdef INET
    bind,
#else
    nosys,
#endif
#ifdef INET
    setsockopt,
#else
    nosys,
#endif
#ifdef INET
    listen,
#else
    nosys,
#endif
    sigsuspend,
    nosys,
    nosys,
    nosys,
    nosys,
    sigstack,
#ifdef INET
    recvmsg,
#else
    nosys,
#endif
#ifdef INET
    sendmsg,
#else
    nosys,
#endif
    nosys,
    gettimeofday,
    getrusage,
#ifdef INET
    getsockopt,
#else
    nosys,
#endif
    nosys,
    readv,
    writev,
    settimeofday,
    fchown,
    fchmod,
#ifdef INET
    recvfrom,
#else
    nosys,
#endif
    nosys,
    nosys,
    rename,
    truncate,
    ftruncate,
    flock,
    nosys,
#ifdef INET
    sendto,
#else
    nosys,
#endif
#ifdef INET
    shutdown,
#else
    nosys,
#endif
#ifdef INET
    socketpair,
#else
    nonet,
#endif
    mkdir,
    rmdir,
    utimes,
    nosys,
    adjtime,
#ifdef INET
    getpeername,
#else
    nosys,
#endif
    nosys,
    nosys,
    getrlimit,
    setrlimit,
    killpg,
    nosys,
    nosys,
    nosys,
#ifdef INET
    getsockname,
#else
    nosys,
#endif
    nosys,
    ustore,
    ufetch,
    ucall,
    nosys,
};

_Static_assert(sizeof(syscall_nargs) / sizeof(syscall_nargs[0]) ==
    sizeof(syscall_handlers) / sizeof(syscall_handlers[0]),
    "syscall metadata arrays differ in length");

_Static_assert(sizeof(syscall_nargs) / sizeof(syscall_nargs[0]) ==
    156, "syscall master count differs from ABI");

const int nsysent =
    sizeof(syscall_handlers) / sizeof(syscall_handlers[0]);
