/*
 * Copyright (c) 1986 Regents of the University of California.
 * All rights reserved.  The Berkeley software License Agreement
 * specifies the terms and conditions for redistribution.
 */

/*
 * Generated by tools/gen_kernel_metadata.py from sys/kern/syscalls.master.
 * Edit the master and run `bmake regen-kernel-metadata`.
 */
#include <sys/param.h>
#include <sys/systm.h>

static const char syscall_name_pool[] =
    "indir\0"
    "exit\0"
    "fork\0"
    "read\0"
    "write\0"
    "open\0"
    "close\0"
    "wait4\0"
    "#8\0"
    "link\0"
    "unlink\0"
    "execv\0"
    "chdir\0"
    "fchdir\0"
    "mknod\0"
    "chmod\0"
    "chown\0"
    "chflags\0"
    "fchflags\0"
    "lseek\0"
    "getpid\0"
    "mount\0"
    "umount\0"
    "__sysctl\0"
    "getuid\0"
    "geteuid\0"
    "ptrace\0"
    "getppid\0"
    "statfs\0"
    "fstatfs\0"
    "getfsstat\0"
    "sigaction\0"
    "sigprocmask\0"
    "access\0"
    "sigpending\0"
    "sigaltstack\0"
    "sync\0"
    "kill\0"
    "stat\0"
    "getlogin\0"
    "lstat\0"
    "dup\0"
    "pipe\0"
    "setlogin\0"
    "profil\0"
    "setuid\0"
    "seteuid\0"
    "getgid\0"
    "getegid\0"
    "setgid\0"
    "setegid\0"
    "kmemdev\0"
    "phys\0"
    "lock\0"
    "ioctl\0"
    "reboot\0"
    "sigwait\0"
    "symlink\0"
    "readlink\0"
    "execve\0"
    "umask\0"
    "chroot\0"
    "fstat\0"
    "#63\0"
    "#64\0"
    "pselect\0"
    "vfork\0"
    "#67\0"
    "#68\0"
    "brk\0"
    "rdglob\0"
    "wrglob\0"
    "msec\0"
    "#73\0"
    "#74\0"
    "#75\0"
    "vhangup\0"
    "#77\0"
    "#78\0"
    "getgroups\0"
    "setgroups\0"
    "getpgrp\0"
    "setpgrp\0"
    "setitimer\0"
    "old wait\0"
    "#85\0"
    "getitimer\0"
    "#87\0"
    "#88\0"
    "getdtablesize\0"
    "dup2\0"
    "#91\0"
    "fcntl\0"
    "select\0"
    "#94\0"
    "fsync\0"
    "setpriority\0"
    "socket\0"
    "connect\0"
    "accept\0"
    "getpriority\0"
    "send\0"
    "recv\0"
    "sigreturn\0"
    "bind\0"
    "setsockopt\0"
    "listen\0"
    "sigsuspend\0"
    "#108\0"
    "#109\0"
    "#110\0"
    "#111\0"
    "sigstack\0"
    "recvmsg\0"
    "sendmsg\0"
    "#115\0"
    "gettimeofday\0"
    "getrusage\0"
    "getsockopt\0"
    "#119\0"
    "readv\0"
    "writev\0"
    "settimeofday\0"
    "fchown\0"
    "fchmod\0"
    "recvfrom\0"
    "#126\0"
    "#127\0"
    "rename\0"
    "truncate\0"
    "ftruncate\0"
    "flock\0"
    "#132\0"
    "sendto\0"
    "shutdown\0"
    "socketpair\0"
    "mkdir\0"
    "rmdir\0"
    "utimes\0"
    "#139\0"
    "adjtime\0"
    "getpeername\0"
    "#142\0"
    "#143\0"
    "getrlimit\0"
    "setrlimit\0"
    "killpg\0"
    "#147\0"
    "setquota\0"
    "quota\0"
    "getsockname\0"
    "#151\0"
    "ustore\0"
    "ufetch\0"
    "ucall\0"
    "#155\0"
    ;

static const uint16_t syscall_name_offsets[] = {
    0, 6, 11, 16, 21, 27, 32, 38, 44, 47, 52, 59,
    65, 71, 78, 84, 90, 96, 104, 113, 119, 126, 132, 139,
    148, 155, 163, 170, 178, 185, 193, 203, 213, 225, 232, 243,
    255, 260, 265, 270, 279, 285, 289, 294, 303, 310, 317, 325,
    332, 340, 347, 355, 363, 368, 373, 379, 386, 394, 402, 411,
    418, 424, 431, 437, 441, 445, 453, 459, 463, 467, 471, 478,
    485, 490, 494, 498, 502, 510, 514, 518, 528, 538, 546, 554,
    564, 573, 577, 587, 591, 595, 609, 614, 618, 624, 631, 635,
    641, 653, 660, 668, 675, 687, 692, 697, 707, 712, 723, 730,
    741, 746, 751, 756, 761, 770, 778, 786, 791, 804, 814, 825,
    830, 836, 843, 856, 863, 870, 879, 884, 889, 896, 905, 915,
    921, 926, 933, 942, 953, 959, 965, 972, 977, 985, 997, 1002,
    1007, 1017, 1027, 1034, 1039, 1048, 1054, 1066, 1071, 1078, 1085, 1091,
};

_Static_assert(sizeof(syscall_name_offsets) /
    sizeof(syscall_name_offsets[0]) == 156,
    "syscall name and ABI counts differ");

const char *
syscall_name(u_int code)
{
    if (code >= (u_int)nsysent)
        return "?";
    return syscall_name_pool + syscall_name_offsets[code];
}
