.\" Copyright (c) 1988 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"	@(#)compat-sys5.3	5.6.1 (2.11BSD) 1996/1/12
.\"
.TH COMPATS5 3 "January 12, 1996"
.UC 7
.SH NAME
memccpy, memchr, memcmp, memcpy, memset, strchr, strrchr, tempnam,
tmpfile, tmpnam \- System V compatibility routines
.SH SYNOPSIS
.nf
.B #include <stdio.h>
.PP
.B char *memccpy(from, to, ch, count)
.B char *from, *to;
.B int ch, count;
.PP
.B char *memchr(str, ch, count)
.B char *str;
.B int ch, count;
.PP
.B int memcmp(str1, str2, count)
.B char *str1, *str2;
.B int count;
.PP
.B char *memcpy(from, to, count)
.B char *from, to;
.B int count;
.PP
.B char *memset(str, ch, count)
.B char *str;
.B int ch, count;
.PP
.B char *strchr(str, ch);
.B char *str;
.B int ch;
.PP
.B char *tempnam(const char *tmpdir, const char *prefix)
.PP
.B FILE *tmpfile(void)
.PP
.B char *tmpnam(char *str)
.SH COMMENT
.I <stdio.h>
defines
.I P_tmpdir
as
.I /tmp/
and defines
.I L_tmpnam
as the 12 bytes required for
.IR /tmp/XXXXXX .
.PP
Also, note that the caveat in the System V manual page that these functions
can start recycling previously used names is untrue in this system.
.SH DESCRIPTION
The above routines are available and behave as in System V.
.PP
.BR tmpfile ()
creates a file with
.BR mkstemp (3),
unlinks the name before returning, and closes the descriptor if stream
construction fails.
.BR tmpnam ()
and
.BR tempnam ()
only choose unused names.  A different process can create those names before
the caller opens them, so callers that create files must use
.BR mkstemp (3)
instead.
.PP
When the argument to
.BR tmpnam ()
is NULL, the function returns a library-owned buffer.  A later call overwrites
the same buffer.
.BR tempnam ()
returns an allocation sized for the selected pathname; the caller releases the
allocation with
.BR free (3).
.PP
.BR strchr ()
and
.BR strrchr ()
are alternate entry points into
.BR index ()
and
.BR rindex ()
respectively.
